apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 574848933676.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 574848933676.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ce6c170e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
